/**
 * codex-format.ts
 * Format adapter for OpenAI Codex CLI — generates a single AGENTS.md file.
 * All rules are combined into one plain Markdown document with ## section headings,
 * following the same pattern as Claude Code's CLAUDE.md format.
 */

import type { SkillRule } from "../../core/skill-types.js";

export interface FormatOutput {
  filename: string;
  content: string;
}

/**
 * Formats skill rules into AGENTS.md content.
 * Returns a single file merging all rules under ## headings.
 */
export function formatRules(rules: SkillRule[]): FormatOutput[] {
  if (rules.length === 0) return [];

  const sections = rules.map((rule) => {
    const heading = `## ${rule.name}`;
    const meta = rule.description ? `\n<!-- ${rule.description} -->\n` : "";
    return `${heading}${meta}\n${rule.content.trim()}`;
  });

  const content = [
    "# Agent Rules",
    "",
    "<!-- Generated by mcpman skill sync. Do not edit manually. -->",
    "",
    sections.join("\n\n"),
    "",
  ].join("\n");

  return [{ filename: "AGENTS.md", content }];
}
