/**
 * codex-agent-format.ts
 * Format adapter for OpenAI Codex CLI agents — generates a single AGENTS.md file.
 * All agents are combined into one Markdown document with ## section headings.
 */

import type { AgentSpec } from "../../core/skill-types.js";

export interface FormatOutput {
  filename: string;
  content: string;
}

/**
 * Formats agent specs into AGENTS.md content.
 * Returns a single file containing all agents as Markdown sections.
 */
export function formatAgents(agents: AgentSpec[]): FormatOutput[] {
  if (agents.length === 0) return [];

  const sections = agents.map((agent) => {
    const lines: string[] = [`# ${agent.name}`];

    if (agent.description) {
      lines.push("", agent.description);
    }

    lines.push("", "## Role", "", agent.role.trim());

    if (agent.instructions) {
      lines.push("", "## Instructions", "", agent.instructions.trim());
    }

    return lines.join("\n");
  });

  const content = [
    "<!-- Generated by mcpman agent sync. Do not edit manually. -->",
    "",
    sections.join("\n\n---\n\n"),
    "",
  ].join("\n");

  return [{ filename: "AGENTS.md", content }];
}
