/**
 * format-adapters.test.ts
 * Tests for all five format adapters: claude-code, cursor, roo-code, codex, windsurf.
 * Each adapter's formatRules() function is tested for output structure and content.
 */

import { describe, expect, it } from "vitest";
import { formatRules as claudeCodeFormatRules } from "../../src/adapters/formats/claude-code-format.js";
import { formatRules as cursorFormatRules } from "../../src/adapters/formats/cursor-format.js";
import { formatRules as rooCodeFormatRules } from "../../src/adapters/formats/roo-code-format.js";
import { formatRules as codexFormatRules } from "../../src/adapters/formats/codex-format.js";
import { formatRules as windsurfFormatRules } from "../../src/adapters/formats/windsurf-format.js";
import type { SkillRule } from "../../src/core/skill-types.js";

// ── Shared fixtures ────────────────────────────────────────────────────────

function makeRule(overrides: Partial<SkillRule> = {}): SkillRule {
  return {
    name: "my-rule",
    content: "Always write clean code.",
    ...overrides,
  };
}

// ── claude-code-format ─────────────────────────────────────────────────────

describe("claude-code-format — formatRules()", () => {
  it("returns empty array for empty rules", () => {
    expect(claudeCodeFormatRules([])).toEqual([]);
  });

  it("returns exactly one file output", () => {
    const outputs = claudeCodeFormatRules([makeRule()]);
    expect(outputs).toHaveLength(1);
  });

  it("output filename is CLAUDE.md", () => {
    const [output] = claudeCodeFormatRules([makeRule()]);
    expect(output.filename).toBe("CLAUDE.md");
  });

  it("content starts with # Project Rules heading", () => {
    const [output] = claudeCodeFormatRules([makeRule()]);
    expect(output.content).toMatch(/^# Project Rules/);
  });

  it("content includes the generated-by comment", () => {
    const [output] = claudeCodeFormatRules([makeRule()]);
    expect(output.content).toContain("Generated by mcpman skill sync");
  });

  it("content contains rule name as ## heading", () => {
    const [output] = claudeCodeFormatRules([makeRule({ name: "my-rule" })]);
    expect(output.content).toContain("## my-rule");
  });

  it("content contains rule content text", () => {
    const [output] = claudeCodeFormatRules([makeRule({ content: "Do the thing." })]);
    expect(output.content).toContain("Do the thing.");
  });

  it("includes HTML comment with description when rule has description", () => {
    const rule = makeRule({ description: "A helpful guideline." });
    const [output] = claudeCodeFormatRules([rule]);
    expect(output.content).toContain("<!-- A helpful guideline. -->");
  });

  it("does not include per-rule description HTML comment when rule has no description", () => {
    // The file always contains the fixed "Generated by" header comment.
    // When a rule has no description, no additional <!-- ... --> block is injected.
    const rule = makeRule({ name: "bare-rule", description: undefined });
    const [output] = claudeCodeFormatRules([rule]);
    // Exactly one comment must exist: the generated-by comment
    const commentMatches = output.content.match(/<!--/g) ?? [];
    expect(commentMatches).toHaveLength(1);
  });

  it("merges multiple rules into a single file separated by blank lines", () => {
    const rules = [
      makeRule({ name: "rule-one", content: "Content one." }),
      makeRule({ name: "rule-two", content: "Content two." }),
    ];
    const [output] = claudeCodeFormatRules(rules);
    expect(output.content).toContain("## rule-one");
    expect(output.content).toContain("## rule-two");
    expect(output.content).toContain("Content one.");
    expect(output.content).toContain("Content two.");
  });

  it("trims whitespace from rule content", () => {
    const rule = makeRule({ content: "  Trimmed content.  " });
    const [output] = claudeCodeFormatRules([rule]);
    expect(output.content).toContain("Trimmed content.");
    expect(output.content).not.toContain("  Trimmed content.  ");
  });
});

// ── cursor-format ──────────────────────────────────────────────────────────

describe("cursor-format — formatRules()", () => {
  it("returns empty array for empty rules", () => {
    expect(cursorFormatRules([])).toEqual([]);
  });

  it("returns one file per rule", () => {
    const rules = [makeRule({ name: "rule-a" }), makeRule({ name: "rule-b" })];
    const outputs = cursorFormatRules(rules);
    expect(outputs).toHaveLength(2);
  });

  it("filename is .cursor/rules/{rule.name}.mdc", () => {
    const [output] = cursorFormatRules([makeRule({ name: "my-rule" })]);
    expect(output.filename).toBe(".cursor/rules/my-rule.mdc");
  });

  it("content starts with YAML frontmatter opening ---", () => {
    const [output] = cursorFormatRules([makeRule()]);
    expect(output.content).toMatch(/^---/);
  });

  it("content contains closing --- to end frontmatter", () => {
    const [output] = cursorFormatRules([makeRule()]);
    const lines = output.content.split("\n");
    // first line is ---, there must be another --- after
    const closingIndex = lines.indexOf("---", 1);
    expect(closingIndex).toBeGreaterThan(0);
  });

  it("includes description in frontmatter when rule has description", () => {
    const rule = makeRule({ description: "TypeScript rules." });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).toContain("description: TypeScript rules.");
  });

  it("does not include description line when rule has no description", () => {
    const rule = makeRule({ description: undefined });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).not.toContain("description:");
  });

  it("includes globs in frontmatter when rule has globs", () => {
    const rule = makeRule({ globs: ["**/*.ts", "**/*.tsx"] });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).toContain("globs: **/*.ts, **/*.tsx");
  });

  it("does not include globs line when rule has no globs", () => {
    const rule = makeRule({ globs: undefined });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).not.toContain("globs:");
  });

  it("does not include globs line when globs is empty array", () => {
    const rule = makeRule({ globs: [] });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).not.toContain("globs:");
  });

  it("includes alwaysApply in frontmatter when defined", () => {
    const rule = makeRule({ alwaysApply: true });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).toContain("alwaysApply: true");
  });

  it("includes alwaysApply: false when explicitly set to false", () => {
    const rule = makeRule({ alwaysApply: false });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).toContain("alwaysApply: false");
  });

  it("does not include alwaysApply when undefined", () => {
    const rule = makeRule({ alwaysApply: undefined });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).not.toContain("alwaysApply:");
  });

  it("content contains the rule content text after frontmatter", () => {
    const rule = makeRule({ content: "Write unit tests for everything." });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).toContain("Write unit tests for everything.");
  });

  it("trims whitespace from rule content", () => {
    const rule = makeRule({ content: "  Clean code.  " });
    const [output] = cursorFormatRules([rule]);
    expect(output.content).toContain("Clean code.");
    expect(output.content).not.toContain("  Clean code.  ");
  });

  it("produces minimal frontmatter (just --- / ---) when no optional fields set", () => {
    const rule: SkillRule = { name: "bare-rule", content: "Content." };
    const [output] = cursorFormatRules([rule]);
    // Should only have opening and closing ---, no other lines in between
    const lines = output.content.split("\n");
    expect(lines[0]).toBe("---");
    expect(lines[1]).toBe("---");
  });
});

// ── roo-code-format ────────────────────────────────────────────────────────

describe("roo-code-format — formatRules()", () => {
  it("returns empty array for empty rules", () => {
    expect(rooCodeFormatRules([])).toEqual([]);
  });

  it("returns one file per rule", () => {
    const rules = [makeRule({ name: "rule-a" }), makeRule({ name: "rule-b" })];
    const outputs = rooCodeFormatRules(rules);
    expect(outputs).toHaveLength(2);
  });

  it("filename is .roo/rules/{rule.name}.md", () => {
    const [output] = rooCodeFormatRules([makeRule({ name: "my-rule" })]);
    expect(output.filename).toBe(".roo/rules/my-rule.md");
  });

  it("content starts with # {rule.name} heading", () => {
    const [output] = rooCodeFormatRules([makeRule({ name: "my-rule" })]);
    expect(output.content).toMatch(/^# my-rule/);
  });

  it("content contains rule content text", () => {
    const rule = makeRule({ content: "Prefer composition." });
    const [output] = rooCodeFormatRules([rule]);
    expect(output.content).toContain("Prefer composition.");
  });

  it("includes description paragraph after heading when present", () => {
    const rule = makeRule({ description: "This covers composition patterns.", content: "Do it." });
    const [output] = rooCodeFormatRules([rule]);
    expect(output.content).toContain("This covers composition patterns.");
  });

  it("does not include description when not set", () => {
    const rule = makeRule({ description: undefined, content: "Content only." });
    const [output] = rooCodeFormatRules([rule]);
    // Heading + blank line + content — no description text
    const lines = output.content.split("\n");
    expect(lines[0]).toBe("# my-rule");
    expect(lines[1]).toBe("");
    // Next non-empty line should be the content itself
    expect(output.content).not.toMatch(/^# my-rule\n\n.+\n\nContent only/);
  });

  it("no YAML frontmatter in output", () => {
    const [output] = rooCodeFormatRules([makeRule()]);
    expect(output.content).not.toContain("---");
  });

  it("trims whitespace from rule content", () => {
    const rule = makeRule({ content: "   Trimmed.   " });
    const [output] = rooCodeFormatRules([rule]);
    expect(output.content).toContain("Trimmed.");
    expect(output.content).not.toContain("   Trimmed.   ");
  });

  it("each rule is written to its own separate file path", () => {
    const rules = [
      makeRule({ name: "alpha" }),
      makeRule({ name: "beta" }),
    ];
    const outputs = rooCodeFormatRules(rules);
    expect(outputs[0].filename).toBe(".roo/rules/alpha.md");
    expect(outputs[1].filename).toBe(".roo/rules/beta.md");
  });
});

// ── codex-format ───────────────────────────────────────────────────────────

describe("codex-format — formatRules()", () => {
  it("returns empty array for empty rules", () => {
    expect(codexFormatRules([])).toEqual([]);
  });

  it("returns exactly one file output", () => {
    const outputs = codexFormatRules([makeRule()]);
    expect(outputs).toHaveLength(1);
  });

  it("output filename is AGENTS.md", () => {
    const [output] = codexFormatRules([makeRule()]);
    expect(output.filename).toBe("AGENTS.md");
  });

  it("content starts with # Agent Rules heading", () => {
    const [output] = codexFormatRules([makeRule()]);
    expect(output.content).toMatch(/^# Agent Rules/);
  });

  it("content includes the generated-by comment", () => {
    const [output] = codexFormatRules([makeRule()]);
    expect(output.content).toContain("Generated by mcpman skill sync");
  });

  it("content contains rule name as ## heading", () => {
    const [output] = codexFormatRules([makeRule({ name: "agent-rule" })]);
    expect(output.content).toContain("## agent-rule");
  });

  it("content contains rule content text", () => {
    const [output] = codexFormatRules([makeRule({ content: "Follow agent protocols." })]);
    expect(output.content).toContain("Follow agent protocols.");
  });

  it("includes HTML comment with description when present", () => {
    const rule = makeRule({ description: "Agent-specific rule." });
    const [output] = codexFormatRules([rule]);
    expect(output.content).toContain("<!-- Agent-specific rule. -->");
  });

  it("does not include per-rule description HTML comment when rule has no description", () => {
    // AGENTS.md always contains the fixed "Generated by" header comment.
    // When a rule has no description, no additional <!-- ... --> block is injected.
    const rule = makeRule({ name: "bare-rule", description: undefined });
    const [output] = codexFormatRules([rule]);
    // Exactly one comment must exist: the generated-by comment
    const commentMatches = output.content.match(/<!--/g) ?? [];
    expect(commentMatches).toHaveLength(1);
  });

  it("merges multiple rules into a single AGENTS.md file", () => {
    const rules = [
      makeRule({ name: "rule-one", content: "Rule one content." }),
      makeRule({ name: "rule-two", content: "Rule two content." }),
    ];
    const [output] = codexFormatRules(rules);
    expect(output.content).toContain("## rule-one");
    expect(output.content).toContain("## rule-two");
  });

  it("trims whitespace from rule content", () => {
    const rule = makeRule({ content: "\n  Trimmed.  \n" });
    const [output] = codexFormatRules([rule]);
    expect(output.content).toContain("Trimmed.");
  });
});

// ── windsurf-format ────────────────────────────────────────────────────────

describe("windsurf-format — formatRules()", () => {
  it("returns empty array for empty rules", () => {
    expect(windsurfFormatRules([])).toEqual([]);
  });

  it("returns one file per rule", () => {
    const rules = [makeRule({ name: "rule-a" }), makeRule({ name: "rule-b" })];
    const outputs = windsurfFormatRules(rules);
    expect(outputs).toHaveLength(2);
  });

  it("filename is .windsurf/rules/{rule.name}.md", () => {
    const [output] = windsurfFormatRules([makeRule({ name: "my-rule" })]);
    expect(output.filename).toBe(".windsurf/rules/my-rule.md");
  });

  it("content starts with # {rule.name} heading", () => {
    const [output] = windsurfFormatRules([makeRule({ name: "my-rule" })]);
    expect(output.content).toMatch(/^# my-rule/);
  });

  it("content contains rule content text", () => {
    const rule = makeRule({ content: "Keep code simple." });
    const [output] = windsurfFormatRules([rule]);
    expect(output.content).toContain("Keep code simple.");
  });

  it("includes description paragraph after heading when present", () => {
    const rule = makeRule({ description: "Windsurf-specific guidance.", content: "Do it." });
    const [output] = windsurfFormatRules([rule]);
    expect(output.content).toContain("Windsurf-specific guidance.");
  });

  it("does not include description when not set", () => {
    const rule = makeRule({ description: undefined, content: "Just content." });
    const [output] = windsurfFormatRules([rule]);
    const lines = output.content.split("\n");
    expect(lines[0]).toBe("# my-rule");
    expect(lines[1]).toBe("");
  });

  it("no YAML frontmatter in output", () => {
    const [output] = windsurfFormatRules([makeRule()]);
    expect(output.content).not.toContain("---");
  });

  it("trims whitespace from rule content", () => {
    const rule = makeRule({ content: "  Trimmed content.  " });
    const [output] = windsurfFormatRules([rule]);
    expect(output.content).toContain("Trimmed content.");
    expect(output.content).not.toContain("  Trimmed content.  ");
  });

  it("each rule is written to its own separate file path", () => {
    const rules = [
      makeRule({ name: "rule-x" }),
      makeRule({ name: "rule-y" }),
    ];
    const outputs = windsurfFormatRules(rules);
    expect(outputs[0].filename).toBe(".windsurf/rules/rule-x.md");
    expect(outputs[1].filename).toBe(".windsurf/rules/rule-y.md");
  });
});
